### ISSUE TITLE
bowtie2 error: FASTA and FASTA formats are mutually exclusive.

### ISSUE THREAD

**Issue by didacs** [algo-cancer/ImmunoTyper-SR#16]
Hi!

I am trying to run `immunotyper-SR` using the docker image `cdslsahinalp/immunotyper-sr` and I am getting the following `bowtie2` error:

```
immunotyper-SR --output_dir /output --output_dir /output --hg37 /bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam
Loading reads from /bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam...
output_path /output/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123-ighv-extracted.fa already exists... Not recruiting reads
Recruited 1015801 reads
Sampled read length: 100
Making allele landmark positions (n=36, groups=6)
Using 50 as minimum number of coding base threshold for mapping filter
Allowing clipped mappings to start within 3 bases of a reference start or end
FASTA and FASTA formats are mutually exclusive.
(ERR): bowtie2-align exited with value 1
Running bowtie2:
bowtie2 -a --end-to-end --very-sensitive -f  --n-ceil C,100,0 --np 0 --ignore-quals --mp 2,2 --score-min C,-50,0 -L 10 -f -x "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/data/allele_databases/IGHV/IGHV-IMGT-allele-db-no_duplicates+Ns.fa" -U "/output/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123-ighv-extracted.fa" -S /tmp/tmpx7tdoqdx
Traceback (most recent call last):
  File "/opt/conda/envs/immunotyper-SR/bin/immunotyper-SR", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/__main__.py", line 126, in main
    run_immunotyper(args.bam_path, args.ref, args.gene_type, args.hg37, args.solver, args.output_dir, args.landmark_groups, args.landmarks_per_group, args.max_copy, args.stdev_coeff, args.seq_error_rate, args.write_cache_path, args.solver_time_limit, args.threads)
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/__main__.py", line 190, in run_immunotyper
    positive, negative = flanking_filter.filter_reads(bam_filter.output_path, mapping_params="-a --end-to-end --very-sensitive -f  --n-ceil C,100,0 --np 0 --ignore-quals --mp 2,2 --score-min C,-50,0 -L 10")
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/read_filter_classes.py", line 46, in filter_reads
    self.positive, self.negative = self.filter(self.map(input_reads))
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/read_filter_classes.py", line 67, in map
    mapping_results = self.mapper.map(reads, self.reference_path,
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/mapper_wrappers.py", line 104, in map
    result = parser(output_path)
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/mapper_wrappers.py", line 115, in sam_parser
    file = pysam.AlignmentFile(output_path, 'rb')
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 956, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
```

It looks like the problem might be a duplicated `-f` flag in the `bowtie2` command. Removing the duplicated flag fixes the error for this command.

To replicate the error:

```
mkdir -p bam
curl -O ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam -o bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam
curl -O ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam.bai -o bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam.bai
```
```
docker run \
  --rm \
  --platform=linux/amd64 \
  -v ./bam:/bam \
  -v ./output:/output \
  --user $(id -u):$(id -g) \
  cdslsahinalp/immunotyper-sr:latest \
    --output_dir /output \
    --hg37 \
    /bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam
```

Thanks!

**Comment by michael-ford** [comment]
Hi! Thanks so much for bringing this up and testing out the solution. I just pushed a new version of the docker image that removes the duplicate `-f`, let me know if you have any further issues!

**Comment by didacs** [comment]
Hi @michael-ford,

Thanks for the quick response! I just pulled the newer image but still get the same error. How can I make sure I am running the new code?

**Comment by didacs** [comment]
Hi @michael-ford ,

Looks like you fixed the issue in your forked repo https://github.com/michael-ford/ImmunoTyper2 but not in the main one?

**Comment by michael-ford** [comment]
Hi @didacs, the dockerhub is currently set to build from that forked repo. It's definitely got the newest commit, but it sounds like that may not have been the solution. I'll have to do some testing and see if I can figure out the bug.

**Comment by michael-ford** [comment]
Hi @didacs turns out there was a problem with how dockerhub was building the image, this should be fixed now

**Comment by didacs** [comment]
Thank you @michael-ford, the bowtie error is now fixed!
