### ISSUE TITLE
GurobiError: HostID mismatch with docker

### ISSUE THREAD

**Issue by didacs** [algo-cancer/ImmunoTyper-SR#18]
Hi!

I am trying to run the tool with docker and a "Free Trial" Gurobi license. I get the following error

```
gurobipy.GurobiError: HostID mismatch (licensed to XXXXXXX, hostid is 0)
```

This is the command

```
docker pull cdslsahinalp/immunotyper-sr
docker run \
  --rm \
  --platform=linux/amd64 \
  -v ./bam:/bam \
  -v ./output:/output \
  -v /Users/didac/gurobi.lic:/opt/gurobi/gurobi.lic \
  --user $(id -u):$(id -g) \
  cdslsahinalp/immunotyper-sr:latest \
    --output_dir /output \
    --hg37 \
    /bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam
```
and the full log

```
Starting ImmunoTyper-SR analysis for IGHV genes on /bam/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam
Initializing allele database
Extracting reads from BAM file
Contig HG1592_PATCH not present in alignment file
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 338985 reads
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 676816 reads
Estimated single copy read depth: 2
Sampled read length: 100
Filtering reads and mapping to allele database
Found 122782 candidate IGHV reads for analysis
Building allele candidates
Generated 651 candidate alleles
Building and solving optimization model
Set parameter Username
Set parameter LicenseID to value XXXXXXX
Traceback (most recent call last):
  File "/opt/conda/envs/immunotyper-SR/bin/immunotyper-SR", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/__main__.py", line 131, in main
    run_immunotyper(args.bam_path, args.ref, args.gene_type, args.hg37, args.solver, args.output_dir, args.landmark_groups, args.landmarks_per_group, args.max_copy, args.stdev_coeff, args.seq_error_rate, args.write_cache_path, args.solver_time_limit, args.threads, args.save_extracted_reads)
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/__main__.py", line 217, in run_immunotyper
    model = implemented_models['ilp'](implemented_solvers[solver], num_landmarks=landmark_groups*landmarks_per_group,
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/models.py", line 102, in __init__
    super(self.__class__, self).__init__('ShortReadModelTotalErrorDiscardObj') #init solver
  File "/opt/conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/solvers.py", line 136, in __init__
    self.model = self.gurobipy.Model(name)
  File "src/gurobipy/model.pxi", line 80, in gurobipy.Model.__init__
  File "src/gurobipy/gurobi.pxi", line 60, in gurobipy.gurobi._getdefaultenv
  File "src/gurobipy/env.pxi", line 70, in gurobipy.Env.__init__
gurobipy.GurobiError: HostID mismatch (licensed to XXXXXXX, hostid is 0)
```

Thanks!

**Comment by michael-ford** [comment]
Hi @didacs what free trial license do you have? If you havent [installed gurobi](https://support.gurobi.com/hc/en-us/articles/360044290292-How-do-I-install-Gurobi-for-Python) on your machine, do so and [then try testing your license](https://support.gurobi.com/hc/en-us/articles/13417565229713-How-do-I-test-my-Gurobi-license).

**Comment by didacs** [comment]
Hi @michael-ford, I did install gurobi and activated the license with `grbgetkey`.  I am not exactly sure what type of license it is, but it says Free Trial
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/7d199d9a-f3bf-4b16-9bb2-5a33c361a6e2" />
\
\
It seems testing the license works fine in my local computer
```
(gurobi) didac@Didacs-MacBook-Pro:/Users/didac $ gurobi_cl --license ~/gurobi.lic
Set parameter Username
Set parameter LicenseID to value 2598758
Set parameter LogFile to value "gurobi.log"
Using license file /Users/didac/gurobi.lic
```
but not inside the docker container, where testing fails

```
docker pull continuumio/miniconda3
docker run \
    -it \
    -v /Users/didac/gurobi.lic:/opt/gurobi/gurobi.lic \
    --platform=linux/amd64 \
    continuumio/miniconda3 /bin/bash
```
```
(base) root@dde5eb4b80f2:/# conda create -y -n immunotyper-SR -c gurobi gurobi
(base) root@dde5eb4b80f2:/# conda activate immunotyper-SR
(immunotyper-SR) root@dde5eb4b80f2:/# gurobi_cl --license /opt/gurobi/gurobi.lic
Set parameter Username
Set parameter LicenseID to value 2598758
Set parameter LogFile to value "gurobi.log"
Using license file /opt/gurobi/gurobi.lic

Failed to set up a license

Error 10009: HostID mismatch (licensed to f3b6fa5d, hostid is 0)
```

Thanks!

**Comment by michael-ford** [comment]
Seems like there are some [potential problems](https://support.gurobi.com/hc/en-us/community/posts/4406485885841-Installing-Gurobi-on-a-Docker-container-Ubuntu) with licenses in docker containers - can you either try the suggested [web license service](https://www.gurobi.com/features/web-license-service/) or try with singularity? We've only tested it on singularity, I assumed docker would work fine but maybe it requires jumping through more hoops.

**Comment by michael-ford** [comment]
Hi @didacs did you manage to get this resolved?

**Comment by didacs** [comment]
Hi @michael-ford, no I did not. I was not able to run singularity on mac.

**Comment by michael-ford** [comment]
Shoot. Did you try installing and running with Conda + Pip?
